 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   annotations:
     kubernetes.io/ingress.class: traefik
   name: ingressctrl-hello-world-travis
   namespace: travis
 spec:
   rules:
     - host: hello-world.travis.ps-vla.madpellzo.org
       http:
         paths:
           - backend:
               serviceName: hello-world-svc-travis
               servicePort: 5000
             path: /
