apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-travis
  namespace: travis
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: hello-world-travis
    spec:
      containers:
      - image: vlandemaineorange/circleci-testing:latest
        imagePullPolicy: Always
        name: hello-world-travis
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
