sudo: required
services:
  - docker

language: python
jobs:
  include:
    - stage: build
      script: |
          docker info
          [ -z "$DOCKER_PASS" ] && echo "Registry Password is not set or empty (or protected) in Secret Variables" && exit 1
          [ -z "$DOCKER_USER" ] && echo "Registry User is not set or empty (or protected) in Secret Variables" && exit 1
          echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
          docker build -t vlandemaineorange/circleci-testing:latest .
          docker push vlandemaineorange/circleci-testing:latest
